version: '3.7'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    hostname: ${DB_HOST}
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgres_db:/var/lib/postgresql/data
    restart: unless-stopped

  backend_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: backend_app
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
    depends_on: 
      - postgres_db