version: '3.7'

services:
    postgres_db:
        image: postgres:latest
        container_name: postgres_db
        hostname: localhost
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: shopper_case_db
        volumes:
            - ./data/postgres_db:/var/lib/postgresql/data
        restart: unless-stopped

    backend_app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/home/node/app/src
            - ./nodemon.json:/home/node/app/nodemon.json
        container_name: backend_app
        expose:
            - '4000'
        ports:
            - '4000:4000'
        environment:
            GEMINI_API_KEY: ${GEMINI_API_KEY}
            DB_HOST: localhost
            DB_NAME: shopper_case_db
            DB_USER: postgres
            DB_PASS: postgres
            DB_PORT: 5432
            BASE_URL: http://localhost:4000
        command: npm run dev
        depends_on:
            - postgres_db
